# -*- coding: utf-8 -*-
"""Machine Learning(Hepatitis C)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnrEcf4dBuWc4wZ4ygJOlflf1NSRrL0V
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/HepatitisCdata.csv', index_col=0)

numerical_columns = ['Age', 'ALB', 'ALP', 'ALT', 'AST', 'BIL', 'CHE', 'CHOL', 'CREA', 'GGT', 'PROT']
df_numerical = df[numerical_columns].apply(pd.to_numeric, errors='coerce')

df_clean = df_numerical.dropna()

corr_matrix = df_clean.corr()

plt.figure(figsize=(12,10))
sns.heatmap(corr_matrix,
            annot=True,
            cmap='coolwarm',
            fmt=".2f",
            linewidths=0.5,
            annot_kws={"size": 10})
plt.title('Correlation Matrix', fontsize=14, pad=20)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(16, 12))
for i, col in enumerate(numerical_columns, 1):
    plt.subplot(4, 3, i)
    sns.boxplot(y=df_clean[col], color='skyblue')
    plt.title(f'{col} Distribution', fontsize=12)
plt.tight_layout()
plt.suptitle('Boxplot Analysis', y=1.02, fontsize=14)
plt.show()

plt.figure(figsize=(16, 12))
for i, col in enumerate(numerical_columns, 1):
    plt.subplot(4, 3, i)
    sns.violinplot(y=df_clean[col], inner='quartile', color='lightgreen')
    plt.title(f'{col} Distribution', fontsize=12)
plt.tight_layout()
plt.suptitle('Violin Plot Analysis', y=1.02, fontsize=14)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.impute import SimpleImputer

data = pd.read_csv('/content/HepatitisCdata.csv')
data = data.dropna()

X = data.drop('Category', axis=1)
y = data['Category']

label_encoder = LabelEncoder()
data['Category'] = label_encoder.fit_transform(data['Category'])
data['Sex'] = label_encoder.fit_transform(data['Sex'])

X = data.drop('Category', axis=1)
y = data['Category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

def plot_confusion_matrix(y_true, y_pred, title='Confusion Matrix'):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title(title)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))
plot_confusion_matrix(y_test, xgb_pred, title='XGBoost Confusion Matrix')

svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
plot_confusion_matrix(y_test, svm_pred, title='SVM Confusion Matrix')

logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
logistic_pred = logistic_model.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, logistic_pred))
plot_confusion_matrix(y_test, logistic_pred, title='Logistic Regression Confusion Matrix')

tree_model = RandomForestClassifier()
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, tree_pred))
plot_confusion_matrix(y_test, tree_pred, title='Decision Tree Confusion Matrix')

from sklearn.model_selection import GridSearchCV

param_grid_xgb = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
}

param_grid_svc = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
}

param_grid_logistic = {
    'C': [0.1, 1, 10],
    'solver': ['lbfgs', 'liblinear'],
}

param_grid_tree = {
    'n_estimators': [50, 100],
    'max_depth': [3, 5, None],
}

def perform_grid_search(model, param_grid, X_train, y_train):
    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')
    grid_search.fit(X_train, y_train)
    return grid_search

xgb_model = XGBClassifier()
best_xgb = perform_grid_search(xgb_model, param_grid_xgb, X_train, y_train)
print("Best XGBoost parameters:", best_xgb.best_params_)
print("Best XGBoost accuracy:", best_xgb.best_score_)

svc_model = SVC()
best_svc = perform_grid_search(svc_model, param_grid_svc, X_train, y_train)
print("Best SVM parameters:", best_svc.best_params_)
print("Best SVM accuracy:", best_svc.best_score_)

logistic_model = LogisticRegression(max_iter=1000)
best_logistic = perform_grid_search(logistic_model, param_grid_logistic, X_train, y_train)
print("Best Logistic Regression parameters:", best_logistic.best_params_)
print("Best Logistic Regression accuracy:", best_logistic.best_score_)

tree_model = RandomForestClassifier()
best_tree = perform_grid_search(tree_model, param_grid_tree, X_train, y_train)
print("Best Decision Tree parameters:", best_tree.best_params_)
print("Best Decision Tree accuracy:", best_tree.best_score_)

xgb_test_pred = best_xgb.predict(X_test)
print("XGBoost Test Accuracy:", accuracy_score(y_test, xgb_test_pred))

svc_test_pred = best_svc.predict(X_test)
print("SVM Test Accuracy:", accuracy_score(y_test, svc_test_pred))

logistic_test_pred = best_logistic.predict(X_test)
print("Logistic Regression Test Accuracy:", accuracy_score(y_test, logistic_test_pred))

tree_test_pred = best_tree.predict(X_test)
print("Decision Tree Test Accuracy:", accuracy_score(y_test, tree_test_pred))

from plotly.subplots import make_subplots
import plotly.graph_objects as haha
fig = make_subplots(rows =10, cols=1,
                    )
Tests_df = df.select_dtypes(include='float')

for i,bio_mark in enumerate(Tests_df.columns):
    fig.add_trace(
        haha.Histogram(x=Tests_df[bio_mark],name=bio_mark),
                    row = i+1,
                    col = 1

    )

fig.update_layout(
    title = "Distribution of Liver Function Biochemical markers",
    height=800,
    width=800,
    showlegend=True
)
fig.show()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

data = pd.read_csv('/content/HepatitisCdata.csv')

label_encoder = LabelEncoder()
data['Category'] = label_encoder.fit_transform(data['Category'])
data['Sex'] = label_encoder.fit_transform(data['Sex'])

X = data.drop('Category', axis=1)
y = data['Category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_test_scaled = scaler.transform(X_test_imputed)

pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_scaled)

pca_df = pd.DataFrame(data=X_train_pca, columns=['Principal Component 1', 'Principal Component 2'])
pca_df['Category'] = y_train.reset_index(drop=True)

plt.figure(figsize=(10, 6))
scatter = plt.scatter(pca_df['Principal Component 1'], pca_df['Principal Component 2'], c=pca_df['Category'], cmap='viridis', alpha=0.7)
plt.title('PCA of Dataset')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar(scatter, label='Category')
plt.grid()
plt.show()

explained_variance = pca.explained_variance_ratio_
print(f"Explained variance by each component: {explained_variance}")
print(f"Total explained variance: {sum(explained_variance)}")

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import plotly.graph_objects as go

data = pd.read_csv('/content/HepatitisCdata.csv')
Hepatitis_numeric = data.select_dtypes(include='float64')

imputer = SimpleImputer(strategy='mean')
Hepatitis_numeric = imputer.fit_transform(Hepatitis_numeric)

scalar = StandardScaler()
df_scaled = scalar.fit_transform(Hepatitis_numeric)

pca = PCA()
pca_result = pca.fit_transform(df_scaled)

fig = go.Figure()

fig.add_trace(go.Scatter(x=list(range(1, len(pca.explained_variance_ratio_) + 1)),
                         y=pca.explained_variance_ratio_,
                         mode='lines+markers',
                         name='Explained Variance Ratio'))

fig.update_layout(title='Explained Variance by Principal Components',
                  xaxis_title='Principal Component',
                  yaxis_title='Explained Variance Ratio',
                 )

fig.show()

"""Explained Variance by principle Components: The figure displays the amount of variance that can be explained by each principle component. The data can be efficiently reduced to fewer dimensions without sacrificing much information, as the first few components account for the majority of the variance.

-The first component explains about 22.4% of the variance.

-The first two components together explain about 38.9% of the variance.

-The first three components explain about 51.3% of the variance.

-The cumulative variance reaches 100% by the 11th component.
"""