# -*- coding: utf-8 -*-
"""Salary Prediction(ML).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_WDsPhtb1n6IPP3Lz9pFIkYqCTsszUU
"""

import pandas as pd

url = "/content/Salary_Data.csv"
data = pd.read_csv(url)


x = data["YearsExperience"]
y = data["Salary"]

import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.font_manager import fontManager

plt.scatter(x, y, marker="x", color="red")
plt.title("Year-Salary")
plt.xlabel("Year")
plt.ylabel("Salary(k)")
plt.show()

def plot_pred(w, b):
  y_pred = x*w + b
  plt.plot(x, y_pred, color="blue", label="pred")
  plt.scatter(x, y, marker="x", color="red", label="real")
  plt.title("Year-Salary")
  plt.xlabel("Year")
  plt.ylabel("Salary(k)")
  plt.legend()
  plt.show()

plot_pred(10, 25)

from ipywidgets import interact

interact(plot_pred, w=(-100, 100, 1), b=(-100, 100, 1))

w = 10
b = 0
y_pred = w*x + b
cost = (y - y_pred)**2
cost.sum() / len(x)

def compute_cost(x, y, w, b):
  y_pred = w*x + b
  cost = (y - y_pred)**2
  cost = cost.sum() / len(x)

  return cost

compute_cost(x, y, 10, 10)

# if b=0 w=-100~100

costs = []
for w in range(-100, 101):
  cost = compute_cost(x, y, w, 0)
  costs.append(cost)
costs

import matplotlib.pyplot as plt

plt.plot(range(-100, 101), costs)
plt.title("cost function b=0 w=-100~100")
plt.xlabel("w")
plt.ylabel("cost")
plt.show()

# if w=-100~100 b=-100~100
import numpy as np

ws = np.arange(-100, 101)
bs = np.arange(-100, 101)
costs = np.zeros((201, 201))

i = 0
for w in ws:
  j = 0
  for b in bs:
    cost = compute_cost(x, y, w, b)
    costs[i,j] = cost
    j = j+1
  i = i+1

costs

import matplotlib as mpl
from matplotlib.font_manager import fontManager

plt.figure(figsize=(8, 8))
ax = plt.axes(projection="3d")
ax.view_init(30, 240)
ax.xaxis.set_pane_color((1.0, 1.0, 1.0))
ax.yaxis.set_pane_color((1.0, 1.0, 1.0))
ax.zaxis.set_pane_color((1.0, 1.0, 1.0))

b_grid, w_grid = np.meshgrid(bs, ws)

ax.plot_surface(w_grid, b_grid, costs, cmap="Spectral_r", alpha=0.8)
ax.plot_wireframe(w_grid, b_grid, costs, color="black", alpha=0.2)

ax.set_title("w b -->cost")
ax.set_xlabel("w")
ax.set_ylabel("b")
ax.set_zlabel("cost")

w_index, b_index = np.where(costs == np.min(costs))
ax.scatter(ws[w_index], bs[b_index], costs[w_index, b_index], color="red", s=38)

plt.show()

print(f"When w={ws[w_index]}, b={bs[b_index]} min. cost:{costs[w_index, b_index]}")

def compute_gradient(x, y, w, b):
  w_gradient = (x*(w*x+b -y)).mean()
  b_gradient = (w*x+b -y).mean()
  return w_gradient, b_gradient

compute_gradient(x, y, 20, 10)

def compute_cost(x, y, w, b):
  y_pred = w*x + b
  cost = (y - y_pred)**2
  cost = cost.sum() / len(x)

  return cost

def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter=1000):

  c_hist = []
  w_hist = []
  b_hist = []

  w = w_init
  b = b_init

  for i in range(run_iter):
    w_gradient, b_gradient = gradient_function(x, y, w, b)

    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    cost = cost_function(x, y, w, b)

    w_hist.append(w)
    b_hist.append(b)
    c_hist.append(cost)

    if i%p_iter == 0:
      print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w: .2e}, b: {b: .2e}, w_gradient: {w_gradient: .2e}, b_gradient: {b_gradient: .2e}")

  return w, b, w_hist, b_hist, c_hist

w_init = 0
b_init = 0
learning_rate = 1.0e-3
run_iter = 20000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x, y, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter)

import matplotlib.pyplot as plt
import numpy as np

plt.plot(np.arange(0, 100), c_hist[:100])
plt.title("iteration vs cost")
plt.xlabel("iteration")
plt.ylabel("cost")
plt.show()

print(f"final w b=({w_final:.2f}, {b_final:.2f})")

print(f"Year3.5  Predicted_Salary:{w_final*3.5 + b_final:.1f}K")
print(f"Year5.9  Predicted_Salary:{w_final*5.9 + b_final:.1f}K")

ws = np.arange(-100, 101)
bs = np.arange(-100, 101)
costs = np.zeros((201, 201))

i = 0
for w in ws:
  j = 0
  for b in bs:
    cost = compute_cost(x, y, w, b)
    costs[i,j] = cost
    j = j+1
  i = i+1

import matplotlib as mpl
from matplotlib.font_manager import fontManager

plt.figure(figsize=(7, 7))
ax = plt.axes(projection="3d")
ax.view_init(20, -65)
ax.xaxis.set_pane_color((1.0, 1.0, 1.0))
ax.yaxis.set_pane_color((1.0, 1.0, 1.0))
ax.zaxis.set_pane_color((1.0, 1.0, 1.0))

b_grid, w_grid = np.meshgrid(bs, ws)

ax.plot_surface(w_grid, b_grid, costs, alpha=0.3)

ax.set_title("w b --> cost")
ax.set_xlabel("w")
ax.set_ylabel("b")
ax.set_zlabel("cost")

w_index, b_index = np.where(costs == np.min(costs))
ax.scatter(ws[w_index], bs[b_index], costs[w_index, b_index], color="red", s=40)
ax.scatter(w_hist[0], b_hist[0], c_hist[0], color="green", s=40)
ax.plot(w_hist, b_hist, c_hist)

plt.show()